AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: WiseUni - Main Stack (Nested Stacks)

Parameters:
  ProjectName:
    Type: String
    Default: wiseuni
    Description: Project name used for resource naming
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name (dev, staging, prod)

Resources:
  # COGNITO STACK
  CognitoStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: stacks/cognito.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        PreSignUpFunctionArn: ""
        PostConfirmationFunctionArn: ""
        PreAuthenticationFunctionArn: ""
        CustomMessageFunctionArn: ""
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # LAMBDA TRIGGERS STACK
  LambdaTriggersStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: CognitoStack
    Properties:
      TemplateURL: stacks/lambda-triggers.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        UserPoolArn: !GetAtt CognitoStack.Outputs.UserPoolArn
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # DATABASE STACK
  DatabaseStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: stacks/database.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # STORAGE STACK
  StorageStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: stacks/storage.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # IAM ROLES STACK
  IAMRolesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: stacks/iam-roles.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        IdentityPoolId: !GetAtt CognitoStack.Outputs.IdentityPoolId
        WiseUniTableArn: !GetAtt DatabaseStack.Outputs.WiseUniTableArn
        HomeworkBucketArn: !GetAtt StorageStack.Outputs.HomeworkBucketArn
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # FRONTEND STACK (✅ NEW!)
  # S3 + CloudFront for static website hosting
  # No dependencies - can deploy in parallel with other stacks
  FrontendStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: stacks/frontend.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

Outputs:
  # COGNITO OUTPUTS
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !GetAtt CognitoStack.Outputs.UserPoolId
    Export:
      Name: !Sub ${ProjectName}-UserPoolId-${Environment}

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !GetAtt CognitoStack.Outputs.UserPoolClientId
    Export:
      Name: !Sub ${ProjectName}-UserPoolClientId-${Environment}

  IdentityPoolId:
    Description: Cognito Identity Pool ID
    Value: !GetAtt CognitoStack.Outputs.IdentityPoolId
    Export:
      Name: !Sub ${ProjectName}-IdentityPoolId-${Environment}

  UserPoolDomain:
    Description: Cognito User Pool Domain
    Value: !GetAtt CognitoStack.Outputs.UserPoolDomain
    Export:
      Name: !Sub ${ProjectName}-UserPoolDomain-${Environment}

  # DATABASE OUTPUTS
  WiseUniTableName:
    Description: DynamoDB Table Name
    Value: !GetAtt DatabaseStack.Outputs.WiseUniTableName
    Export:
      Name: !Sub ${ProjectName}-TableName-${Environment}

  WiseUniTableArn:
    Description: DynamoDB Table ARN
    Value: !GetAtt DatabaseStack.Outputs.WiseUniTableArn
    Export:
      Name: !Sub ${ProjectName}-TableArn-${Environment}

  # STORAGE OUTPUTS
  HomeworkBucketName:
    Description: S3 Bucket Name (for file uploads)
    Value: !GetAtt StorageStack.Outputs.HomeworkBucketName
    Export:
      Name: !Sub ${ProjectName}-BucketName-${Environment}

  HomeworkBucketArn:
    Description: S3 Bucket ARN
    Value: !GetAtt StorageStack.Outputs.HomeworkBucketArn
    Export:
      Name: !Sub ${ProjectName}-BucketArn-${Environment}

  # IAM OUTPUTS
  StudentRoleArn:
    Description: Student IAM Role ARN
    Value: !GetAtt IAMRolesStack.Outputs.StudentRoleArn
    Export:
      Name: !Sub ${ProjectName}-StudentRoleArn-${Environment}

  ProfessorRoleArn:
    Description: Professor IAM Role ARN
    Value: !GetAtt IAMRolesStack.Outputs.ProfessorRoleArn
    Export:
      Name: !Sub ${ProjectName}-ProfessorRoleArn-${Environment}

  AdminRoleArn:
    Description: Admin IAM Role ARN
    Value: !GetAtt IAMRolesStack.Outputs.AdminRoleArn
    Export:
      Name: !Sub ${ProjectName}-AdminRoleArn-${Environment}

  # FRONTEND OUTPUTS
  FrontendBucketName:
    Description: S3 bucket for frontend static files
    Value: !GetAtt FrontendStack.Outputs.FrontendBucketName
    Export:
      Name: !Sub ${ProjectName}-FrontendBucketName-${Environment}

  CloudFrontDistributionId:
    Description: CloudFront distribution ID
    Value: !GetAtt FrontendStack.Outputs.CloudFrontDistributionId
    Export:
      Name: !Sub ${ProjectName}-CloudFrontDistributionId-${Environment}

  CloudFrontDomainName:
    Description: CloudFront domain name
    Value: !GetAtt FrontendStack.Outputs.CloudFrontDomainName
    Export:
      Name: !Sub ${ProjectName}-CloudFrontDomain-${Environment}

  WebsiteURL:
    Description: 🌐 Your WiseUni website URL (click to visit!)
    Value: !GetAtt FrontendStack.Outputs.WebsiteURL
    Export:
      Name: !Sub ${ProjectName}-WebsiteURL-${Environment}
