AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: WiseUni - Main Stack (imports all nested stacks)

Parameters:
  ProjectName:
    Type: String
    Default: wiseuni
    Description: Project name prefix for resources

  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name

# NESTED STACKS
Resources:
  # ----- COGNITO STACK -----
  CognitoStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: stacks/cognito.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        # Pass Lambda ARNs for triggers
        PreSignUpFunctionArn: !GetAtt LambdaTriggersStack.Outputs.PreSignUpFunctionArn
        PostConfirmationFunctionArn: !GetAtt LambdaTriggersStack.Outputs.PostConfirmationFunctionArn
        PreAuthenticationFunctionArn: !GetAtt LambdaTriggersStack.Outputs.PreAuthenticationFunctionArn
        CustomMessageFunctionArn: !GetAtt LambdaTriggersStack.Outputs.CustomMessageFunctionArn

  # ----- DATABASE STACK -----
  DatabaseStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: stacks/database.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment

  # ----- STORAGE STACK -----
  StorageStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: stacks/storage.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment

  # ----- IAM ROLES STACK -----
  IAMRolesStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - CognitoStack
      - DatabaseStack
      - StorageStack
    Properties:
      TemplateURL: stacks/iam-roles.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        IdentityPoolId: !GetAtt CognitoStack.Outputs.IdentityPoolId
        WiseUniTableArn: !GetAtt DatabaseStack.Outputs.WiseUniTableArn
        HomeworkBucketArn: !GetAtt StorageStack.Outputs.HomeworkBucketArn

  # ----- LAMBDA TRIGGERS STACK -----
  # Note: This must be created BEFORE CognitoStack
  LambdaTriggersStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: stacks/lambda-triggers.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment

# Aggregated outputs from nested stacks
Outputs:
  # Cognito
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !GetAtt CognitoStack.Outputs.UserPoolId

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !GetAtt CognitoStack.Outputs.UserPoolClientId

  IdentityPoolId:
    Description: Cognito Identity Pool ID
    Value: !GetAtt CognitoStack.Outputs.IdentityPoolId

  HostedUILoginURL:
    Description: Hosted UI Login URL
    Value: !GetAtt CognitoStack.Outputs.HostedUILoginURL

  # Database
  WiseUniTableName:
    Description: DynamoDB Table Name
    Value: !GetAtt DatabaseStack.Outputs.WiseUniTableName

  # Storage
  HomeworkBucketName:
    Description: S3 Bucket Name
    Value: !GetAtt StorageStack.Outputs.HomeworkBucketName
